---
title: "data_cleaning"
format: html
edtiro: visual
---

# Libraries

```{r}
library("tidyverse")
```

# Cleaning table 1

```{r}
#| echo: false
dirty_1 <- read_tsv(file = "../data/dirty_data/supp_1.tsv")
```

# Cleaning table 2 Louise
#Want to remove all SD rows
```{r}
#| echo: false

#reading the tsv file
dirty_2 <-read_tsv(file = "../data/dirty_data/supp_2.tsv")

#checking
View(dirty_2)

#Want to remove all SD columns (from column nr 21-38), but keep all else
clean_2 <- dirty_2 |> 
  select(1:20, 39:40, 42:43)

#3 remaining column headers; Isolated cells, Brain regions, cerebellum development

#Isolated cells table
clean_2_isolated_cells <- clean_2 |> 
  select(1:6, 21:24)

#Brain region table
clean_2_brain_regions <- clean_2 |> 
  select(1:2, 7:17, 21:24)
  
#Cerebellum dev table
clean_2_cerebellum_development <- clean_2 |>
  select(1:2, 18:20, 21:24)


View(clean_2)
View(clean_2_cerebellum_development)
```

# Cleaning table 3

```{r}
#| echo: false
dirty_3 <- read_tsv(file = "../data/dirty_data/supp_3.tsv")
```


# Cleaning table 5

```{r}
#| echo: false
dirty_5 <- read_tsv(file = "../data/dirty_data/supp_5.tsv")
```
